CREATE TABLE SETTINGS (
    id INT PRIMARY KEY,
    user_id INT,
    sound_alerts BOOLEAN,
    vibration_alerts BOOLEAN,
    date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela PAYMENT
CREATE TABLE PAYMENT (
    NUM INT PRIMARY KEY,
    NUM_VENDEDOR INT,
    NUM_CLIENTE INT,
    DATA DATE,
    HORA TIME,
    date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);